import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test('операция обновляет обзор и бюджет, лимиты разделены по месяцам', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/transactions/new')
  await page.getByRole('button', { name: 'Сохранить операцию' }).click()
  await expect(page.getByText('Проверьте выделенные поля.')).toBeVisible()
  await page.getByLabel('Сумма, ₽').fill('1250,50')
  await page.getByRole('combobox', { name: 'Категория', exact: true }).click()
  await page.getByRole('option', { name: 'Продукты', exact: true }).click()
  await page.getByLabel('Комментарий').fill('Проверка покупки')
  await page.getByRole('button', { name: 'Сохранить операцию' }).click()
  await expect(page).toHaveURL(/\/transactions$/)
  await expect(page.getByText('Проверка покупки')).toBeVisible()
  await page.getByRole('link', { name: 'Обзор', exact: true }).click()
  await expect(page.getByTestId('expense-total')).toHaveText(/29\s?566,00/)
  await page.getByRole('link', { name: 'Бюджеты', exact: true }).click()
  const food = page.getByRole('region', { name: 'Продукты', exact: true })
  await expect(food).toContainText(/4\s?501,00/)
  await page.getByLabel('Лимит, ₽').fill('4000')
  await page.getByRole('button', { name: 'Сохранить лимит' }).click()
  await expect(food).toContainText('Превышение: 501,00')
  const month = await page.getByLabel('Месяц').inputValue()
  await page.getByLabel('Месяц').fill('2020-01')
  await expect(food).toContainText('Лимит не задан')
  await page.getByLabel('Месяц').fill(month)
  await expect(food).toContainText('Превышение: 501,00')
  await page.reload()
  await expect(food).toContainText(/Лимит: 15\s?000,00/)
  await expect(food).toContainText(/Потрачено: 3\s?250,50/)
  expect(errors).toEqual([])
})

test('фильтры, отмена, история, прямые адреса и тема', async ({ page }) => {
  await page.goto('/transactions')
  await page.getByLabel('Тип операции').click()
  await page.getByRole('option', { name: 'Доход', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Найдено: 2')
  await page.getByLabel('Месяц').fill('2020-01')
  await expect(page.getByText('Операции не найдены.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await expect(page.getByRole('status')).toHaveText('Найдено: 6')
  await page.getByRole('link', { name: 'Добавить операцию' }).click()
  await page.getByLabel('Сумма, ₽').fill('100')
  await page.getByRole('link', { name: 'Отмена', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Найдено: 6')
  await page.getByRole('link', { name: 'Бюджеты', exact: true }).click()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Операции', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Бюджеты', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Настройки', exact: true }).click()
  await page.getByRole('switch', { name: 'Тёмная тема' }).check()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(16, 26, 22)')
  await page.reload()
  await expect(page.getByRole('switch', { name: 'Тёмная тема' })).toBeChecked()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(16, 26, 22)')
  await page.getByRole('switch', { name: 'Тёмная тема' }).uncheck()
  await page.goto('/missing')
  await expect(page.getByRole('heading', { name: 'Страница не найдена' })).toBeVisible()
  await page.getByRole('link', { name: 'Открыть обзор', exact: false }).click()
  await expect(page).toHaveURL(/\/$/)
})

test('все экраны без переполнения на телефоне и скриншоты', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await mkdir('docs/screenshots', { recursive: true })
  const screens = [ ['/', 'overview', 'Обзор'], ['/transactions', 'transactions', 'Операции'], ['/transactions/new', 'new-transaction', 'Новая операция'], ['/budgets', 'budgets', 'Бюджеты'], ['/settings', 'settings', 'Настройки'], ['/missing', 'not-found', 'Страница не найдена'] ]
  for (const width of [1440, 320]) {
    await page.setViewportSize({ width, height: width === 320 ? 800 : 1000 })
    for (const [path, name, title] of screens) {
      await page.goto(path)
      await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await page.screenshot({ path: `docs/screenshots/${name}${width === 320 ? '-mobile' : ''}.png`, fullPage: true, animations: 'disabled' })
    }
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/settings')
  await page.getByRole('switch', { name: 'Тёмная тема' }).check()
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(16, 26, 22)')
  await page.screenshot({ path: 'docs/screenshots/settings-dark.png', fullPage: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Обзор', exact: true })).toBeVisible()
  await page.screenshot({ path: 'docs/screenshots/overview-dark.png', fullPage: true })
  expect(errors).toEqual([])
})
