import { test, expect } from './fixtures.js'
import { chooseMonth } from './month-picker.js'

test('своя категория сохраняется и доступна в операциях, бюджете и обзоре', async ({ page }) => {
  await page.goto('/transactions/new')
  await expect(page.locator('.MuiFormLabel-asterisk:visible')).toHaveCount(0)
  await page.getByRole('button', { name: 'Добавить свою категорию' }).click()
  await page.getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await expect(page.getByText('Введите название от 1 до 80 символов.')).toBeVisible()
  await page.getByLabel('Название категории').fill('Мои покупки')
  await page.getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Категория', exact: true })).toContainText('Мои покупки')
  await page.getByLabel('Сумма, ₽').fill('250')
  await page.getByRole('button', { name: 'Сохранить операцию' }).click()
  await expect(page).toHaveURL(/\/transactions$/)
  await expect(page.getByText('Мои покупки')).toBeVisible()
  await page.goto('/budgets')
  await page.getByRole('combobox', { name: 'Категория', exact: true }).click()
  await page.getByRole('option', { name: 'Мои покупки', exact: true }).click()
  await page.getByLabel('Лимит, ₽').fill('500')
  await page.getByRole('button', { name: 'Сохранить лимит' }).click()
  await expect(page.getByRole('region', { name: 'Мои покупки', exact: true })).toContainText('Лимит: 500,00')
  await page.reload()
  await expect(page.getByRole('region', { name: 'Мои покупки', exact: true })).toContainText('Потрачено: 250,00')
  await page.getByRole('button', { name: 'Добавить свою категорию' }).click()
  await page.getByLabel('Название категории').fill('Мои покупки')
  await page.getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await expect(page.getByText('Категория с таким названием уже существует.')).toBeVisible()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await chooseMonth(page, '2020-01')
  await expect(page.getByRole('textbox', { name: 'Месяц', exact: true })).toHaveValue('январь 2020')
  await page.goto('/')
  await chooseMonth(page, '2020-02')
  await expect(page.getByRole('textbox', { name: 'Месяц', exact: true })).toHaveValue('февраль 2020')
  await expect(page.getByRole('alert').filter({ hasText: 'Операций за этот месяц нет' })).toHaveCount(2)
})

