import { test, expect, authorized, createAccount } from './fixtures.js'
import type { Page } from '@playwright/test'
import { chooseMonth } from './month-picker.js'

async function capture(page: Page, name: string) {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.getByRole('status', { name: 'Загрузка данных' })).toHaveCount(0)
  for (const width of [1440, 320]) {
    await page.setViewportSize({ width, height: width === 320 ? 800 : 1000 })
    await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `docs/screenshots/${name}${width === 320 ? '-mobile' : ''}.png`, fullPage: true, animations: 'disabled' })
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
}

test('CRUD операции пересчитывает обзор и бюджеты, изменения и удаление сохраняются в БД', async ({ page, context, account }) => {
  await page.goto('/transactions/new')
  await page.getByLabel('Сумма, ₽').fill('100')
  await page.getByRole('combobox', { name: 'Категория', exact: true }).click()
  await page.getByRole('option', { name: 'Продукты', exact: true }).click()
  await page.getByLabel('Комментарий').fill('Лаба 5 CRUD')
  await page.getByRole('button', { name: 'Сохранить операцию' }).click()
  const card = page.getByRole('listitem').filter({ hasText: 'Лаба 5 CRUD' })
  await card.getByRole('link', { name: 'Редактировать' }).click()
  const editURL = page.url()
  const id = editURL.split('/').at(-2)!
  await expect(page.getByLabel('Сумма, ₽')).toHaveValue('100,00')
  await capture(page, 'edit-transaction')
  await page.getByLabel('Сумма, ₽').fill('0')
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await expect(page.getByLabel('Сумма, ₽')).toHaveAttribute('aria-invalid', 'true')
  await page.getByLabel('Сумма, ₽').fill('500')
  await page.getByRole('combobox', { name: 'Категория', exact: true }).click()
  await page.getByRole('option', { name: 'Транспорт', exact: true }).click()
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await expect(card).toContainText('500,00')
  await expect(card).toContainText('Транспорт')
  await page.reload()
  await expect(card).toContainText('500,00')
  await page.getByRole('link', { name: 'Обзор', exact: true }).click()
  await expect(page.getByTestId('expense-total')).toHaveText(/28\s?815,50/)
  await page.getByRole('link', { name: 'Бюджеты', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Транспорт', exact: true })).toContainText('Потрачено: 565,00')
  await expect(page.getByRole('region', { name: 'Продукты', exact: true })).toContainText(/Потрачено: 3\s?250,50/)
  await page.goto(editURL)
  await page.getByLabel('Дата', { exact: false }).fill('15.01.2020')
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await page.getByRole('link', { name: 'Обзор', exact: true }).click()
  await expect(page.getByTestId('expense-total')).toHaveText(/28\s?315,50/)
  await chooseMonth(page, '2020-01')
  await expect(page.getByTestId('expense-total')).toHaveText('500,00 ₽')
  await page.getByRole('link', { name: 'Операции', exact: true }).click()
  await card.getByRole('button', { name: 'Удалить операцию' }).click()
  await capture(page, 'delete-transaction')
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: 'Удалить операцию' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(card).toHaveCount(0)
  await page.reload()
  await expect(card).toHaveCount(0)
  await expect(page.getByRole('status')).toHaveText('Найдено: 6')
  const remaining: { id: string }[] = await (await authorized(context.request, account, 'GET', '/transactions')).json()
  expect(remaining.some((item) => item.id === id)).toBe(false)
  await page.goto(editURL)
  await expect(page.getByRole('heading', { name: 'Операция недоступна' })).toBeVisible()
})

test('удаление и повторное создание лимита сохраняют операции и другие месяцы', async ({ page, context, account }) => {
  await page.goto('/budgets')
  const food = page.getByRole('region', { name: 'Продукты', exact: true })
  await food.getByRole('button', { name: 'Удалить лимит' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(food).toContainText('Лимит не задан')
  await expect(food).toContainText(/Потрачено: 3\s?250,50/)
  await expect(page.getByRole('region', { name: 'Жильё', exact: true })).toContainText(/Лимит: 25\s?000,00/)
  await page.reload()
  await expect(food).toContainText('Лимит не задан')
  await chooseMonth(page, '2020-01')
  await page.getByLabel('Лимит, ₽').fill('1000')
  await page.getByRole('button', { name: 'Сохранить лимит' }).click()
  await expect(food).toContainText(/Лимит: 1\s?000,00/)
  await chooseMonth(page, new Date().toLocaleDateString('sv-SE', { timeZone: 'Europe/Moscow' }).slice(0, 7))
  await expect(food).toContainText('Лимит не задан')
  await page.getByLabel('Лимит, ₽').fill('4000')
  await page.getByRole('button', { name: 'Сохранить лимит' }).click()
  await expect(food).toContainText(/Лимит: 4\s?000,00/)
  await page.getByLabel('Лимит, ₽').fill('4500')
  await page.getByRole('button', { name: 'Сохранить лимит' }).click()
  await expect(food).toContainText(/Лимит: 4\s?500,00/)
  await page.reload()
  await expect(food).toContainText(/Лимит: 4\s?500,00/)
  await chooseMonth(page, '2020-01')
  await expect(food).toContainText(/Лимит: 1\s?000,00/)
  const transactions = await (await authorized(context.request, account, 'GET', '/transactions')).json()
  expect(transactions).toHaveLength(6)
})

test('управление категориями: переименование связей, запреты и удаление свободной категории', async ({ page }) => {
  await page.goto('/categories')
  await capture(page, 'categories')
  const food = page.getByRole('listitem').filter({ hasText: 'Продукты' })
  await food.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await page.getByLabel('Название категории').fill('Покупки')
  await page.getByRole('button', { name: 'Сохранить категорию' }).click()
  const purchases = page.getByRole('listitem').filter({ hasText: 'Покупки' })
  await expect(purchases).toBeVisible()
  await page.getByRole('link', { name: 'Операции', exact: true }).click()
  await expect(page.getByRole('listitem').filter({ hasText: 'Покупки на неделю' })).toContainText('Покупки')
  await page.getByRole('link', { name: 'Бюджеты', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Покупки', exact: true })).toContainText(/Лимит: 15\s?000,00/)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Покупки', exact: true })).toContainText(/Потрачено: 3\s?250,50/)
  await page.getByRole('link', { name: 'Категории', exact: true }).click()
  await purchases.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await page.getByRole('combobox', { name: 'Тип категории' }).click()
  await page.getByRole('option', { name: 'Доход', exact: true }).click()
  await page.getByRole('button', { name: 'Сохранить категорию' }).click()
  await expect(page.getByText('Нельзя менять тип категории с операциями или бюджетами.')).toBeVisible()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await purchases.getByRole('button', { name: 'Удалить категорию' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(page.getByText('Нельзя удалить категорию с операциями или бюджетами.')).toBeVisible()
  await capture(page, 'category-delete-error')
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  await page.getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await page.getByLabel('Название категории').fill('Свободная')
  await page.getByRole('dialog').getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  const free = page.getByRole('listitem').filter({ hasText: 'Свободная' })
  await free.getByRole('button', { name: 'Редактировать', exact: true }).click()
  await page.getByRole('combobox', { name: 'Тип категории' }).click()
  await page.getByRole('option', { name: 'Доход', exact: true }).click()
  await page.getByRole('button', { name: 'Сохранить категорию' }).click()
  await expect(page.getByRole('heading', { name: 'Доходы', exact: true }).locator('..').getByText('Свободная', { exact: true })).toBeVisible()
  await free.getByRole('button', { name: 'Удалить категорию' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(free).toHaveCount(0)
  await page.reload()
  await expect(free).toHaveCount(0)
})

test('ошибки доступа, валидации и сети не меняют данные; запрос можно повторить', async ({ page }) => {
  await page.goto('/transactions')
  const card = page.getByRole('listitem').filter({ hasText: 'Покупки на неделю' })
  await card.getByRole('link', { name: 'Редактировать' }).click()
  await page.getByLabel('Сумма, ₽').fill('999')
  for (const [status, detail, expected] of [
    [403, 'Нет доступа к этой операции.', 'Нет доступа к этой операции.'],
    [422, [{ loc: ['body', 'amount_kopecks'], msg: 'Invalid' }], 'Проверьте правильность введённых данных.'],
  ] as const) {
    await page.route('**/api/transactions/*', (route) => route.fulfill({ status, json: { detail } }))
    await page.getByRole('button', { name: 'Сохранить изменения' }).click()
    await expect(page.getByText(expected)).toBeVisible()
    await expect(page.getByLabel('Сумма, ₽')).toHaveValue('999')
    await page.unroute('**/api/transactions/*')
  }
  await page.getByRole('link', { name: 'Отмена', exact: true }).click()
  await expect(card).toContainText(/3\s?250,50/)
  await card.getByRole('button', { name: 'Удалить операцию' }).click()
  await page.route('**/api/transactions/*', (route) => route.abort('failed'))
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(page.getByText('Не удалось связаться с сервером.', { exact: false })).toBeVisible()
  await page.unroute('**/api/transactions/*')
  await page.getByRole('dialog').getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(card).toHaveCount(0)
  await page.reload()
  await expect(card).toHaveCount(0)
})

test('списки API загружаются полностью при количестве операций больше 100', async ({ page, context, account }) => {
  const categories: { id: string; name: string }[] = await (await authorized(context.request, account, 'GET', '/categories')).json()
  const category = categories.find((item) => item.name === 'Продукты')!
  for (let index = 0; index < 101; index++) {
    await authorized(context.request, account, 'POST', '/transactions', {
      category_id: category.id, amount_kopecks: 1, date: '2020-01-01', comment: `Пагинация ${index}`,
    })
  }
  await page.goto('/transactions')
  await expect(page.getByRole('status')).toHaveText('Найдено: 107')
  await page.getByLabel('Дата', { exact: true }).fill('01.01.2020')
  await expect(page.getByRole('status')).toHaveText('Найдено: 101')
  await page.getByRole('link', { name: 'Обзор', exact: true }).click()
  await chooseMonth(page, '2020-01')
  await expect(page.getByTestId('expense-total')).toHaveText('1,01 ₽')
})


test('реальная пустая выборка категорий и создание категории через интерфейс', async ({ page, context }) => {
  const emptyAccount = await createAccount(context.request)
  const categories: { id: string }[] = await (await authorized(context.request, emptyAccount, 'GET', '/categories')).json()
  for (const category of categories) await authorized(context.request, emptyAccount, 'DELETE', `/categories/${category.id}`)
  await page.goto('/categories')
  await expect(page.getByText('Категорий пока нет')).toBeVisible()
  await capture(page, 'categories-empty')
  await page.getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await page.getByLabel('Название категории').fill('Первая категория')
  await page.getByRole('dialog').getByRole('button', { name: 'Добавить категорию', exact: true }).click()
  await expect(page.getByRole('listitem').filter({ hasText: 'Первая категория' })).toBeVisible()
  await expect(page.getByText('Категорий пока нет')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('listitem').filter({ hasText: 'Первая категория' })).toBeVisible()
  await page.getByRole('link', { name: 'Операции', exact: true }).click()
  await page.getByRole('link', { name: 'Добавить операцию', exact: true }).click()
  await page.getByRole('combobox', { name: 'Категория', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Первая категория', exact: true })).toBeVisible()
})
